logging:
  file:
    path: logs/app.${spring.application.name}.log
    max-size: 100MB
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka